apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-flask
  labels:
    app: qed-flask
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-flask
    spec:
      containers:
      - name: qed-flask
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
        env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        volumeMounts:
          - mountPath: /src/collected-static
            name: collected-static
          - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin
            name: sam-bin
          - mountPath: /src/hms-flask/data/qed-basins
            name: qed-basins
          - mountPath: /src/pvolume
            name: flask-pvolume
      restartPolicy: Always
      volumes:
      - name: collected-static
        hostPath:
          path: data/collected-static
          type: Directory
      - name: sam-bin
        hostPath:
          path: data/sam-bin
          type: Directory
      - name: qed-basins
        hostPath:
          path: data/qed-basins
          type: Directory