apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-django
  labels:
    app: qed-django
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-django
    spec:
      containers:
      - name: qed-django
        image: quanted/qed-django
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
        env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        volumeMounts:
          - mountPath: /src/collected_static
            name: collected-static
          - mountPath: /src/templates_qed
            name: qed-templates
          - mountPath: /src/static_qed
            name: qed-static
          - mountPath: /src/secrets
            name: django-secrets
          - mountPath: /src/django_pvolume
            name: django-pvolume
      restartPolicy: Always
      volumes:
      - name: collected-static
        hostPath:
          path: data/collected-static
          type: Directory
      - name: qed-templates
        hostPath:
          path: templates_qed
          type: Directory
      - name: qed-static
        hostPath:
          path: static_qed
          type: Directory
      - name: django-secrets
        hostPath:
          path: data/django-secrets
          type: Directory
