apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-celery
  labels:
    app: qed-celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-celery
    spec:
      containers:
      - name: qed-celery
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: "Always"
        command:
        - celery
        - "worker"
        - "-A"
        - "celery_cgi"
        - "-Q"
        - "qed"
        - "--loglevel=DEBUG"
        - "-n"
        - "qed-worker"
        env:
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        volumeMounts:
        - mountPath: /src/pram_flask/ubertool/ubertool/sam/bin
          name: sam-bin
        - mountPath: /src/hms_flask/data/qed-basins
          name: qed-basins
        #- mountPath: /src/pvolume
        #  name: celery-pvolume
      restartPolicy: Always
      volumes:
      - name: sam-bin
        hostPath:
          path: data/sam-bin
          type: Directory
      - name: qed-basins
        hostPath:
          path: data/qed-basins
          type: Directory