apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pvolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis-pv1
  hostPath:
    path: {{PWD}}/data/pv-redis