apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: celery-flower
  name: celery-flower
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery-flower
    spec:
      containers:
      - command:
        - celery
        - flower
        - --broker=redis://redis:6379
        - --url-prefix=flower
        image: mher/flower
        imagePullPolicy: Always
        name: celery-flower
        ports:
        - containerPort: 5555
        volumeMounts:
        - mountPath: /src
          name: qed-flask
      restartPolicy: Always
      volumes:
      - hostPath:
          path: K:\qed_kube\flask_qed
        name: qed-flask
