apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dask-worker
  name: dask-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dask-worker
    spec:
      containers:
      - command:
        - dask-worker
        - dask-scheduler:8786
        env:
        - name: IN_DOCKER
          value: 'True'
        - name: PYTHONPATH
          value: /src:/src/qed
        - name: UBERTOOL_REST_SERVER
          value: http://qed-nginx:7777
        image: quanted/qed-dask
        name: dask-worker
        volumeMounts:
        - mountPath: /src
          name: qed-django
      hostname: dask-worker
      restartPolicy: Always
      volumes:
      - name: qed-django
        persistentVolumeClaim:
          claimName: qed-django-pvolume-claim1

