apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  generation: 9
  labels:
    app: dask-worker
  name: dask-worker
  namespace: qed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-worker
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask-worker
    spec:
      containers:
      - command:
        - dask-worker
        - dask-scheduler:8786
        env:
        - name: AURORA_PW
          valueFrom:
            secretKeyRef:
              key: nta_pass.txt
              name: ms2-db-creds
        - name: IN_DOCKER
          value: "True"
        - name: PYTHONPATH
          value: /src:/src/qed
        - name: UBERTOOL_REST_SERVER
          value: http://qed-nginx:7777
        image: quanted/qed-dask
        imagePullPolicy: Always
        name: dask-worker
        volumeMounts:
        - mountPath: /src
          name: qed-django
      hostname: dask-worker
      restartPolicy: Always
      volumes:
      - name: qed-django
        persistentVolumeClaim:
          claimName: qed-django-pvolume-claim1

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dask-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dask-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50