apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pvolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: C:\git\qed_kube\data\pv-mongodb
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mongodb-pv1
  volumeMode: Filesystem
