apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: K:\qed_kube\data\pv-postgres
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: postgres-pv1
  volumeMode: Filesystem
