apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvolume-claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
