apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: quanted/postgres
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/sql/
          name: postgres-pvolume
      terminationGracePeriodSeconds: 10
      volumes:
      - name: postgres-pvolume
        persistentVolumeClaim:
          claimName: postgres-pvolume-claim1
