apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvolume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: C:\git\qed_kube\data\hms-databases
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: postgres-pv1
  volumeMode: Filesystem
