apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-django
  name: qed-django
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-django
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        image: quanted/qed-django
        imagePullPolicy: Always
        name: qed-django
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src/collected_static
          name: collected-static
        - mountPath: /src/temp_config
          name: temp-config
        - mountPath: /src/templates_qed
          name: qed-templates
        - mountPath: /src/static_qed
          name: qed-static
        - mountPath: /src/secrets
          name: django-secrets
        - mountPath: /src/django_pvolume
          name: django-pvolume
      restartPolicy: Always
      volumes:
      - hostPath:
          path: K:\qed_kube\data\collected-static
          type: Directory
        name: collected-static
      - hostPath:
          path: K:\qed_kube\temp_config
          type: Directory
        name: temp-config
      - hostPath:
          path: K:\qed_kube\templates_qed
          type: Directory
        name: qed-templates
      - hostPath:
          path: K:\qed_kube\static_qed
          type: Directory
        name: qed-static
      - hostPath:
          path: K:\qed_kube\data\django-secrets
          type: Directory
        name: django-secrets
