apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-flask
  name: qed-flask
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-flask
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: Always
        name: qed-flask
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src/collected-static
          name: collected-static
        - mountPath: /src/flask-bin
          name: flask-bin
      restartPolicy: Always
      volumes:
      - hostPath:
          path: C:\git\qed_kube\data\collected-static
          type: Directory
        name: collected-static
      - hostPath:
          path: C:\git\qed_kube\data\flask-bin
          type: Directory
        name: flask-bin
