apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-flask
  name: qed-flask
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-flask
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        image: quanted/flask_qed:dev
        imagePullPolicy: Always
        name: qed-flask
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src/collected-static
          name: collected-static
        - mountPath: /src/app-data
          name: app-data
      restartPolicy: Always
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1
      - name: collected-static
        persistentVolumeClaim:
          claimName: collected-static-pvolume-claim1
