apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qed-nginx-certs-pvolume-claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
