apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 2
  labels:
    app: qed-celery
  name: qed-celery
  namespace: qed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qed-celery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-celery
    spec:
      containers:
      - command:
        - celery
        - worker
        - -A
        - celery_cgi
        - -Q
        - qed
        - --loglevel=DEBUG
        - -n
        - qed-worker
        - --uid=nobody
        - --gid=nogroup
        env:
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        image: quanted/flask_qed:dev_mc
        imagePullPolicy: Always
        name: qed-celery
        volumeMounts:
        - mountPath: /src
          name: qed-flask
        - mountPath: /src/app-data
          name: app-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: qed-flask
        persistentVolumeClaim:
          claimName: qed-flask-pvolume-claim1
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvolume-claim1