apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-flask
  name: qed-flask
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-flask
    spec:
      containers:
      - env:
        - name: REDIS_HOSTNAME
          value: redis
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: Always
        name: qed-flask
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src/collected-static
          name: collected-static
        - mountPath: /src/pram-flask/ubertool/ubertool/sam/bin
          name: sam-bin
        - mountPath: /src/hms-flask/data/qed-basins
          name: qed-basins
        - mountPath: /src/pvolume
          name: flask-pvolume
      restartPolicy: Always
      volumes:
      - hostPath:
          path: K:\qed_kube\data\collected-static
          type: Directory
        name: collected-static
      - hostPath:
          path: K:\qed_kube\data\sam-bin
          type: Directory
        name: sam-bin
      - hostPath:
          path: K:\qed_kube\data\qed-basins
          type: Directory
        name: qed-basins
