apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-celery
  name: qed-celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-celery
    spec:
      containers:
      - command:
        - celery
        - worker
        - -A
        - celery_cgi
        - -Q
        - qed
        - --loglevel=DEBUG
        - -n
        - qed-worker
        env:
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: Always
        name: qed-celery
        volumeMounts:
        - mountPath: /src/pram_flask/ubertool/ubertool/sam/bin
          name: sam-bin
        - mountPath: /src/hms_flask/data/qed-basins
          name: qed-basins
      restartPolicy: Always
      volumes:
      - hostPath:
          path: K:\qed_kube\data\sam-bin
          type: Directory
        name: sam-bin
      - hostPath:
          path: K:\qed_kube\data\qed-basins
          type: Directory
        name: qed-basins
