apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cts-worker
  name: cts-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cts-worker
    spec:
      containers:
      - args:
        - celery
        - worker
        - -A
        - tasks
        - -Q
        - cts_queue
        - -l
        - info
        - -n
        - cts_worker
        - -c
        - "2"
        env:
        - name: DOCKER_HOSTNAME
          value: QED_KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        image: quanted/cts_celery:dev
        name: worker-cts
      restartPolicy: Always