apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cts-nodejs
  name: cts-nodejs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cts-nodejs
    spec:
      containers:
      - env:
        - name: NODEJS_HOST
          value: cts_nodejs
        - name: NODEJS_PORT
          value: "4000"
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: quanted/cts_nodejs:dev
        name: cts-nodejs
      restartPolicy: Always
