apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dask-scheduler
  name: dask-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        image: quanted/qed-dask
        name: dask-scheduler
        ports:
          - containerPort: 8786
          - containerPort: 8787
      hostname: dask-scheduler
      restartPolicy: Always