apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hms-dotnetcore
  labels:
    app: hms-dotnetcore
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hms-dotnetcore
    spec:
      containers:
      - image: quanted/hms-dotnetcore
        name: hms-dotnetcore
        imagePullPolicy: "Always"
        env:
          - name: FLASK_SERVER
            value: http:\\qed-nginx:7777
        volumeMounts:
        - mountPath: /app/App_Data
          name: hms-dotnetcore-appdata
      restartPolicy: Always
      volumes:
      - name: hms-dotnetcore-appdata
        hostPath:
          path: hms/Web.Services/App_Data
          type: Directory