apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: postgres-pv1
  hostPath:
    path: data/pv-postgres