apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qed-tomcat
  name: qed-tomcat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-tomcat
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xmx512m
        image: quanted/qed-tomcat
        name: qed-tomcat
        volumeMounts:
        - mountPath: /usr/local/tomcat/
          name: qed-tomcat-config
      restartPolicy: Always
      volumes:
      - hostPath:
          path: data/tomcat-secrets/
        name: qed-tomcat-config
