apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qed-celery
  labels:
    app: qed-celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qed-celery
    spec:
      containers:
      - name: qed-celery
        image: quanted/flask_qed:dev_kube
        imagePullPolicy: "Always"
        command:
        - celery
        - "worker"
        - "-A"
        - "celery_cgi"
        - "-Q"
        - "qed"
        - "--loglevel=DEBUG"
        - "-n"
        - "qed-worker"
        env:
        - name: DOCKER_HOSTNAME
          value: QED-KUBERNETES
        - name: REDIS_HOSTNAME
          value: redis
        volumeMounts:
        - mountPath: /src/app-data
          name: app-data
      restartPolicy: Always
      volumes:
      - name: app-data
        hostPath:
          path: data/app-data
          type: Directory
